### ISSUE TITLE
How to show props from imported and extend packages that are using the dist version

### ISSUE THREAD

**Issue by NeilMcEachin** [vue-styleguidist/vue-styleguidist#1304]
I have a dropdown component that extends vue-multiselect

```
<script>
import VueMultiselect from 'vue-multiselect';

export default {
  name: 'GDropdown',
  extends: VueMultiselect,
  inheritAttrs: false,
  components: {
    VueMultiselect,
  },
  methods: {},
};
</script>
```

When I do this the props from vue-multiselect do not get added to doc page
I configured `validExtends` to include it

```
validExtends(fullFilePath) {
    return (
      /[\\/]src[\\/]components[\\/]/.test(fullFilePath) ||
      /[\\/]node_modules[\\/]vue-multiselect[\\/]/.test(fullFilePath) ||
      !/[\\/]node_modules[\\/]/.test(fullFilePath)
    );
  },
```

I noticed if I directly set it to use the vue component then they will show up
```import VueMultiselect from 'vue-multiselect/src/Multiselect.vue';```

Is this a bug? Or will vsg only parse extended .vue files?

**Comment by philgruneich** [comment]
@NeilMcEachin did you ever resolve this? I have this behavior for anything coming from node_modules even if I set validExtends to `() => true`

**Comment by elevatebart** [comment]
The way Vue Styleguidist works is by statically looking at the code of the SFC. The compiled component is minified, modified and cannot be analyzed.
If the SFC is referenced, then no problem. I could see this getting fixed by reading the sourcemaps and figure out which source file to analyze. But I know nothing (yet) about how sourcemaps work.

If one of you is interested in looking into it it would be a pleasure for me to understand and check the PR.

**Comment by philgruneich** [comment]
In my case I've tried a couple of things: created 2 sibling SFC, one extended the other and used vue-docgen-cli to generate the docs. The generated docs had the props from the component that was extended. I've tried a few other things and everything worked, until I threw the component in the node_modules folder, then regardless of bruteforcing my `validExtends` option it would still not parse the props.

I'm assuming I'm doing something wrong with the validExtends configuration, I just don't have a clue on what that would be.

**Comment by philgruneich** [comment]
I've created something akin to a MRE here: https://github.com/philgruneich/mre-valid-extends. In the docgen.config.js file I'm trying to block extends from the "invalid_extend" folder and allow extends from the "primevue" folder (which is in node_modules). Neither works (the generated docs are also committed so no one has to clone the project just to see the output).

**Comment by philgruneich** [comment]
So, the short solution is: add `jsx: false` to your apiOptions in the docgen.config.js file.

This is because in the first run through `getRequiredComponents` (parseSFC.ts) we're adding `jsx: false` to the options even if it is undefined in the DocGenOptions. This hides the issue in the `isOptionsObject` function (main.ts):

```
function isOptionsObject(opts: any): opts is DocGenOptions {
	return (
		!!opts &&
		(!!opts.alias ||
			opts.jsx !== undefined ||
			!!opts.addScriptHandlers ||
			!!opts.addTemplateHandlers)
	)
}
```

If `opts.alias` is undefined it will check if `opts.jsx` is not undefined. In the first run through `getRequiredComponents` the value is set to false as default and therefore this function will return true. However, if jsx is undefined, let's say, by only having `validExtends` in your options object, this function will return false. This is relevant because in the `parsePrimitive` (main.ts) we're defining the ParseOptions and if `isOptionsObject` returns false we override the `validExtends` from the options with the default one.
