### ISSUE TITLE
functions in addScriptHandlers are not being called in vue-docgen-api

### ISSUE THREAD

**Issue by abdul-alhasany** [vue-styleguidist/vue-styleguidist#1326]
**Current behavior**
When adding new handlers to addScriptHandlers, they are not being called by vue-docgen-api
**To reproduce**
This is the code that I am using 
```javascript
import { ScriptHandlers, TemplateHandlers, parse } from 'vue-docgen-api';

const componentInfoSimple = await parse(filePath, {
  alias: { '@assets': 'src/assets' },
  jsx: false,
  scriptHandlers: [ScriptHandlers.componentHandler],
  templateHandlers: [TemplateHandlers.slotHandler],
  addScriptHandlers: [
    /**
     * @param {Documentation} documentation
     * @param {NodePath} componentDefinition
     * @param {bt.File} astPath
     * @param {ParseOptions} options
     * @return {Promise<void>}
     */
    function (documentation, componentDefinition, astPath, options) {
      // Code here is not being executed
      console.log('Custom handler');
    },
  ],
});
```

componentInfoSimple returns json data with correct props, slots ... etc. But is not calling custom handler.

I even tried to add the callback in "scriptHandlers" property to override default handlers, but was not successful. 

**Expected behavior**
Custom handler to be called. i.e. "Customer handler" text to be printed in console when running the file in node.

**Comment by elevatebart** [comment]
Hello @kalimah-apps ,

That's a bummer, I do not think those functions are actually e2e tested. 
Let me make sure they are tested and I will try your code.

In the meantime, I would really appreciate a reproduction. It helps make sure that your specific situation is resolved.

Thank you in advance.
Bart

**Comment by abdul-alhasany** [comment]
@elevatebart Thanks for fixing this issue so quickly. 
Is there a projection when this change will be available through npm as the pull request still not closed yet.
