### ISSUE TITLE
Why the mixin is not displayed in doc?

### ISSUE THREAD

**Issue by rshaibakov** [vue-styleguidist/vue-styleguidist#134]
I have a mixin for a text field:
```js
/**
 * @mixin
 */
export default {
  props: {
    /**
     * Name field
     */
    name: {
      type: String,
      required: true,
      default: ''
    },
    /**
     * Type field
     */
    type: {
      type: String,
      required: false,
      default: 'text'
    },
    /**
     * Value field
     */
    value: {
      type: [Array, String, Number],
      required: false,
      default: ''
    },
    ...
```
Apply mixin in component:
```js
import Input from 'mixins/input'

/**
 * Text field component
 */
export default {
  name: 'ui-input',

  mixins: [Input],

  props: {
  ...
```

But in cookbook, the props of mixin are not visible in the component, even though it works. Am I doing something wrong?

**vue-styleguidist version - 1.7.6**

**Comment by hgascoigne** [comment]
I've actually been running into the same issue with 1.7.7. I've double (quadruple) checked that my code matches the example given in the docs.

**Comment by rafaesc** [comment]
It's possible that vue-docgen-api can't find the file because it doesn't recognize the alias `import Input from 'mixins/input'`. You could fix if you put the complete reference of mixin file without the alias.

**Comment by hgascoigne** [comment]
@rafaesc You're right. If I change `import color from 'mixins/color'` to `import color from '../mixins/color'` it works fine. Thanks!

**Comment by rshaibakov** [comment]
@rafaesc  I have a lot of aliases in project. And that's sad for me. In the future this will be as the fixed? Or not worth wait?

**Comment by rafaesc** [comment]
@rshaibakov, you are right, vue-docgen-api should support customized alias.

For the moment I am working on router feature, but you can create a PR.
Where it tries to find the file mixin is here:
https://github.com/vue-styleguidist/vue-docgen-api/blob/master/src/utils/getMixin.js#L9-L20

Feel free to send a pull request ;-)

**Comment by rafegoldberg** [comment]
Just came across this issue myself:
```js
import myMix from '@/mixins/myMix'` 

export default {
  mixins: [myMix]
}
```
Changing it to `'../mixins/mix.js'` "fixed" the issue. But this isn't _really_ a solution, seeing how the *`@`* alias is actually part of Vue core and all!

**Comment by elevatebart** [comment]
can you guys try it again with vue 3.0 ?
duplicate of #158

**Comment by elevatebart** [comment]
I was thinking of using Vue-cli-plugin-styleguidist

Bart Ledoux
Twitter: @bartledoux
Github: @elevatebart

**Comment by elevatebart** [comment]
hey @rafegoldberg, I have implemented aliases and moudles from webpack in the core of styleguidist.
I hope this will help you get your docs.

**Comment by rafegoldberg** [comment]
@elevatebart sick dude, just saw your last ^note! Somewhat busy with other projects at the moment, but will def. check out the newest version and report back when I have a chance...

**Comment by elevatebart** [comment]
Thank you @rafegoldberg

**Comment by dflock** [comment]
This still appears to affect @public methods in mixins loaded with aliases?
