### ISSUE TITLE
vue-docgen support mixin

### ISSUE THREAD

**Issue by beyzacaliskan** [vue-styleguidist/vue-styleguidist#687]
Hi,

I have a question about vue-docgen-loader support mixin. When a component is created using mixin, I can not see the props that come from mixin. I created checkbox component using selectable mixin and added indeterminate props.

```
import Selectable from '../../components/selectable'

export default {
  name: 'my-checkbox',

  mixins: [
    Selectable
  ],
  props: {
    indeterminate: Boolean,
  }
```
I am using vue-docgen-loader in my webpack.config.js file.
When I write a story for checkbox component I didn't see props of selectable component. I saw only indeterminate prop in the props table. How can I show props come from selectable component?

Thanks

**Comment by sense-it-gmbh** [comment]
Same here. In my case the mixin is a named import in case that matters.

vue-cli-plugin-styleguidist: 4.2.3
vue-styleguidist: 4.2.3

**Comment by elevatebart** [comment]
Hey @beyzacaliskan @sense-it-gmbh , 
In some cases, docgen has issues resolving where mixins are in a file.
Is it possible for you to share the outline of your mixin files?

The most important part is the way you export the mixins.

Thank you

**Comment by sense-it-gmbh** [comment]
`/src/mixins/MxDeprecated`:
```js
// @vue/component
/**
 * Mark the component as **deprecated**.
 *
 * When the component is used somewhere in the application an error is printed to the console.
 *  Messages are suppressed if `process.env.NODE_ENV === 'production'`.
 * @mixin
 */
export const MxDeprecated = {
  created () {
    if (process.env.NODE_ENV !== 'production') {
      console.error(`[${this.$options.name}] DEPRECATED! Do not use this component anymore!`)
    }
  }
}
```

`/src/mixins/index.js`:
```js
// [...]
export * from '@/mixins/MxDeprecated'
```

`/src/components/MyColorPicker.vue`:
```js
// [...]
import picker from 'vuetify/es5/mixins/picker'
import colors from 'vuetify/es5/util/colors'

import { MxHasModel } from '@/mixins'

/**
 * A picker component for choosing colors.
 */
export default {
  name: 'SitColorPicker',
  mixins: {
    MxHasModel,
    picker
  },
  props: {
    /**
     * Title to display within the picker.
     *  If omitted a localized default is used.
     */
    title: {
      type: String,
      default: null
    }
  }
// [...]
}
// [...]
```

**Comment by elevatebart** [comment]
Hello @sense-it-gmbh Can you please try 4.3.0? it should be working for your case now.

**Comment by sense-it-gmbh** [comment]
Hi @elevatebart its working fine now here! Thank you for your fast reaction!

**Comment by elevatebart** [comment]
Hello @beyzacaliskan, 

vue-docgen-api is a static analysis tool. 
It looks at your code and finds patterns but never execute it.
So if the Checkbox props are completely indetermined, it will not see them. If they are explicitly coded in the mixin, in other words not being added at runtime to the object, then any component using the mixin will detect the props and document them.

**Comment by beyzacaliskan** [comment]
Hi @elevatebart,

Thanks for your fast response. I tried version 4.3.0 but it still not working.

I am sharing my checkbox.js and selectable mixin files.

MyCheckbox.js
```js
import Selectable from '../../components/selectable'

export default {
  name: 'my-checkbox',

  mixins: [
    Selectable
  ],
  props: {
    indeterminate: Boolean,
  }
....
```

selectable.js (mixin file)

```js
// Components
import MyInput from '../components/MyInput'

// Mixins
import Rippleable from './rippleable'
import Comparable from './comparable'

/* @vue/component */
export default MyInput.extend({
  name: 'selectable',

  mixins: [Rippleable, Comparable],

  model: {
    prop: 'inputValue',
    event: 'change'
  },

  props: {
    color: {
      type: String,
      default: 'primary'
    },
    id: String,
    inputValue: null,
    falseValue: null,
    trueValue: null,
    multiple: {
      type: Boolean,
      default: null
    },
    label: String
  },
```

I want to see props of selectable.js file with my checkbox component props.

Thanks in advance

**Comment by elevatebart** [comment]
I believe what you want was delivered in 4.4 with the vuetify exports components. Let me try it out and confirm it.

**Comment by elevatebart** [comment]
I added a test with your mixin and it works ;)

https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-docgen-api/tests/components/jsfile/button-js.test.ts
